# Generated by Django 5.1.4 on 2025-02-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=30, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('location', models.TextField(blank=True, max_length=50, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('soft_skills_required', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True, max_length=1000, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApp.job')),
            ],
        ),
        migrations.CreateModel(
            name='S_candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=30, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('location', models.TextField(blank=True, max_length=50, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('soft_skills_required', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True, max_length=1000, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApp.job')),
            ],
        ),
    ]
