# Generated by Django 5.1.4 on 2025-02-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_company',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
