# Generated by Django 5.1.4 on 2025-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True, max_length=20, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('skill_required', models.JSONField(blank=True, default=list)),
                ('soft_skills_required', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
